version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ci
hooks:
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_service.sh
      timeout: 3600
      runas: ec2-user